### ISSUE TITLE
Circular dependencies, recursive types and type spreading

### ISSUE THREAD

**Issue by nojaf** [rescript-lang/experimental-rescript-webapi#2]
As most of us, may have somewhat expected, the DOM has cyclic dependencies between types.

Example case:

Types `Window`, `Document` and `Node`. 

The property [window.document](https://developer.mozilla.org/en-US/docs/Web/API/Window/document) means `type document` needs to be known before `type window`.

[Document](https://developer.mozilla.org/en-US/docs/Web/API/Document) inherits from [Node](https://developer.mozilla.org/en-US/docs/Web/API/Node), so `Node` needs to be known to `Document` to be able to spread.

[Node.ownerDocument](https://developer.mozilla.org/en-US/docs/Web/API/Node/ownerDocument) returns a `document` from `node` thus creating a loop.

```res
type rec node = {
    ownerDocument: Null.t<document>,
}

and document = {
    ...node
}

and window = {
    document: document;
}

/*
Syntax Errors
[E] Line 10, column 22:
Did you forget a `,` here?
 */
```

Spreading does not work here and duplicating the properties leads to

```res
type rec node = {ownerDocument: Null.t<document>}

and document = {ownerDocument: Null.t<document>}

and window = {document: document}

// Compiled with 1 Warning(s)
// [W] Line 3, column 16:
// the label ownerDocument is defined in both types node and document.
```

It is my understanding that https://github.com/TheSpyder/rescript-webapi uses all the types defined in `node_modules/rescript/lib/ocaml/dom.ml`, I can no longer find this file in the current ReScript compiler though. It is my understanding that we also no longer what to use that.

Anyway, feels like back to the drawing board.
Suggestions to model this are welcome!

**Comment by zth** [comment]
We can turn off that warning locally in the file(s) as needed:

```rescript
@@warning("-30")

type rec node = {ownerDocument: Null.t<document>}

and document = {ownerDocument: Null.t<document>}

and window = {document: document}
```

This yields no warning. So that would be an acceptable approach still I think. 

But, it'd be good to only duplicate props only when needed, and still spread them when we're not in a recursive chain.

**Comment by zth** [comment]
> It is my understanding that https://github.com/TheSpyder/rescript-webapi uses all the types defined in `node_modules/rescript/lib/ocaml/dom.ml`, I can no longer find this file in the current ReScript compiler though. It is my understanding that we also no longer what to use that.

The file is here now: https://github.com/rescript-lang/rescript-compiler/blob/master/runtime/Dom.res

**Comment by nojaf** [comment]
Thanks for pointing that out. I believe we will need an initial chain of recursive types where we repeat the properties. Once we have those, we can have some edge types which can use spreading.

**Comment by zth** [comment]
> Thanks for pointing that out. I believe we will need an initial chain of recursive types where we repeat the properties. Once we have those, we can have some edge types which can use spreading.

Sounds like a good approach!

**Comment by nojaf** [comment]
Alright, when it comes to the interfaces I believe we have three categories: the precursors, the chain and the spreaders.

The precursors are interfaces which are used in the chain and need to be defined first.
They are pretty standalone I believe.

Examples:
```
"DOMTokenList",
"NamedNodeMap",
"Location",
"FragmentDirective",
"DocumentTimeline",
"History",
"CustomElementRegistry",
// https://developer.mozilla.org/en-US/docs/Web/API/Window/locationbar
"BarProp",
"Navigator",
"Screen",
"VisualViewport",
"SpeechSynthesis"
```

Then there is a chain of recursive types (which thus cannot use spreading)

Examples:

```
"Node",
"NodeList",
"Element",
"ShadowRoot",
"HTMLElement",
"HTMLCollection",
"HTMLHeadElement",
"DOMImplementation",
"DocumentType",
"Document",
"Window",
```

The chain has circular dependencies and needs to copy all properties of its base interfaces.
Once that chain is established, we will be able to use spreading again.

Example:
```
HTMLButtonElement
HTMLInputElement
...
```

**Comment by zth** [comment]
One question that comes to mind - do we have circular dependencies in the _spreads_ too? Or is the problem mainly that spreads, as of now, simply aren't allowed in recursive definitions?

If it's the latter, one could look into what it'd take to allow spreading in recursive definitions in the compiler, provided we can find a way to error out if the spread happens to be circular.

**Comment by nojaf** [comment]
Good point, I would need to check that.

**Comment by cristianoc** [comment]
I think it would be pretty interesting to just describe what ideal typing for DOM would look like, to begin with, and separately check what is supported today and what might be needed in terms of extensions.
I'm not even sure the DOM has ever been typed properly at all.

**Comment by nojaf** [comment]
> do we have circular dependencies in the spreads too? 

It appears that https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet and https://developer.mozilla.org/en-US/docs/Web/API/CSSRule have a nested thing going on.

This is not necessarily a problem, it might be fine to have multiple chains that need to be emitted in order.

**Comment by nojaf** [comment]
Alright, I made some progress, all interfaces are now generated in one huge file!
This file is not perfect but could serve as a good enough basis to start copying over into various modules.

> I think it would be pretty interesting to just describe what ideal typing for DOM would look like, to begin with

This one is difficult to answer, I guess the key thing is that we want a new attempt at modelling the Web APIs using records.

This allow us to do things like:

```res
external window: window = "window"
let href = window.location.href // because window is a record and location is.
```

This feels very familiar to newcomers.

> I'm not even sure the DOM has ever been typed properly at all.

Probably not and it really is an overwhelming task. I'd like to setup this new project in way that has 80% of what people need and it easy to contribute anything that is missing. Docs and guides will be key there. 

Next step is too look at methods.

**Comment by cristianoc** [comment]
> As most of us, may have somewhat expected, the DOM has cyclic dependencies between types.
> 
> Example case:
> 
> Types `Window`, `Document` and `Node`.
> 
> The property [window.document](https://developer.mozilla.org/en-US/docs/Web/API/Window/document) means `type document` needs to be known before `type window`.
> 
> [Document](https://developer.mozilla.org/en-US/docs/Web/API/Document) inherits from [Node](https://developer.mozilla.org/en-US/docs/Web/API/Node), so `Node` needs to be known to `Document` to be able to spread.
> 
> [Node.ownerDocument](https://developer.mozilla.org/en-US/docs/Web/API/Node/ownerDocument) returns a `document` from `node` thus creating a loop.
> 
> ```rescript
> type rec node = {
>     ownerDocument: Null.t<document>,
> }
> 
> and document = {
>     ...node
> }
> 
> and window = {
>     document: document;
> }
> 
> /*
> Syntax Errors
> [E] Line 10, column 22:
> Did you forget a `,` here?
>  */
> ```
> 
> Spreading does not work here and duplicating the properties leads to
> 
> ```rescript
> type rec node = {ownerDocument: Null.t<document>}
> 
> and document = {ownerDocument: Null.t<document>}
> 
> and window = {document: document}
> 
> // Compiled with 1 Warning(s)
> // [W] Line 3, column 16:
> // the label ownerDocument is defined in both types node and document.
> ```
> 
> It is my understanding that https://github.com/TheSpyder/rescript-webapi uses all the types defined in `node_modules/rescript/lib/ocaml/dom.ml`, I can no longer find this file in the current ReScript compiler though. It is my understanding that we also no longer what to use that.
> 
> Anyway, feels like back to the drawing board. Suggestions to model this are welcome!

Some experiments (I'm using optional fields to avoid visual distractions):

```res
type node<'document> = {ownerDocument?: 'document}

type rec document = {
  ...node<document>,
  someNode?: node<document>
}

type window = {document: document}

let doc: document = {}
let node: node<_> = {}
let rec doc2 = n => n <= 0 ? {ownerDocument: doc2(n - 1)} : {someNode: node}
```

On the playground:
https://rescript-lang.org/try?version=v11.1.4&module=esmodule&code=C4TwDgpgBAdg9gEwgHgOQLgYwK4FsIzAB8UAvFAN5wDuMEATgCJZ4HAD8AXFOi-oQF8AUENCQo9CJigYc-YGUpCoUAHTr4SZLNaEiAGmVQAznHwA5RBC6wr2vmyJDho8NGoBLGBmqKKO+W4AthcAGwgFWSCHQj9hcIVNCG4k5AB9EnIKeIiJKRksACZFGDISUuRyAAYodkoaOiYY4GjMQoAKUoBaKABGAEoBKG4KUwsrFKthIA

**Comment by cometkim** [comment]
Given that `Node` and `Element` have different purposes, there is also a way to eliminate circular dependency by not expressing their inheritance relationship.

```res
type node = {  }

type element = {  }

type document = {  }

external documentNode: document => node = "%identity"
external elementNode: element => node = "%identity"

@get external ownerDocument: node => Nullable.t<document> = "ownerDocument"

let toElement: node => option<element> = /* Node can be converted only when nodeType === ELEMENT_TYPE */
```

Another option I tried is to make it ADT so possible to pattern match

```res
@tag("tagName")
type htmlInputElement = | @as("INPUT") HTMLInputElement({})
@tag("tagName")
type htmlDivElement = | @as("DIV") HTMLDivElement({})

@tag("tagName")
type element = | ...htmlInputElement | ...htmlDivElement

type document = {
  activeElement: Null.t<element>,
}

@tag("nodeType")
type node = | @as(1) Element(element) | @as(9) Document(document)


let node = Element(HTMLInputElement({}))
```

but need more improvement https://github.com/rescript-lang/rescript-compiler/issues/6547

**Comment by nojaf** [comment]
Documented the current approach in https://rescript-lang.github.io/experimental-rescript-webapi/02-api-module-structure/#interfaces
