### ISSUE TITLE
Wrong binding of `fetch_withRequest`

### ISSUE THREAD

**Issue by stephanoskomnenos** [rescript-lang/experimental-rescript-webapi#37]
https://github.com/rescript-lang/experimental-rescript-webapi/blob/main/src/Global.res#L496-L509

`@send` should be removed

**Comment by nojaf** [comment]
Hello, thanks for reporting this issue!
I believe you are right, this might have happened when refactoring this method on the Window type.
Are you interested in sending a PR for this?
