### ISSUE TITLE
Module names/namespace

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/experimental-rescript-webapi#8]
Just adding `@rescript/webapi` to you `bs-dependencies` will now pollute your namespace with lots of modules.

IMHO the organization should be similar to the old https://github.com/TheSpyder/rescript-webapi where there was a single `Webapi` root module (with the other modules being prefixed with `Webapi__`).

Then, if you want to bring everything into scope, you can do `open Webapi`, otherwise you just use `Webapi.window`, `Webapi.Location` etc.

**Comment by nojaf** [comment]
Sounds reasonable, would like to go for `WebAPI` though.
As `API` is an acronym, https://developer.mozilla.org/en-US/docs/Web/API

**Comment by nojaf** [comment]
@zth was is the difference with adding `namespace: true` like in https://github.com/zth/rescript-bun/blob/6d227d76148e7c3d428cec699ace25a8e830c1e8/rescript.json#L5C2-L5C21 ?

**Comment by fhammerschmidt** [comment]
With namespace, you don't need to prefix files manually, but you also lose the possibility to have some extra functions in root: https://github.com/TheSpyder/rescript-webapi/blob/main/src/Webapi.res

btw. you would need to set

```json
"namespace": "WebAPI"
```
to have the casing you mentioned above.

**Comment by zth** [comment]
cc @jfrolich who's been doing some extensions of namespaces for Rewatch.

**Comment by nojaf** [comment]
@cknitt I tried out that namespace setting: https://github.com/nojaf/my-pkmn-rescript-app/pull/2
(Thanks @fhammerschmidt for example)

I would go with this setting if that works for you.

**Comment by cknitt** [comment]
I think this is fine. So if I do

```-open WebAPI.Global```

I get the various global instances + functions in scope, plus the most important APIs (to be discussed which those are?).

And if I additionally do

```-open WebAPI```

I will have all of the WebAPI modules in scope.

Correct?
